# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pluginm_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pluginmDialogBase(object):
    def setupUi(self, pluginmDialogBase):
        pluginmDialogBase.setObjectName("pluginmDialogBase")
        pluginmDialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(pluginmDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")

        self.retranslateUi(pluginmDialogBase)
        self.button_box.accepted.connect(pluginmDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(pluginmDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(pluginmDialogBase)

    def retranslateUi(self, pluginmDialogBase):
        _translate = QtCore.QCoreApplication.translate
        pluginmDialogBase.setWindowTitle(_translate("pluginmDialogBase", "pluginm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pluginmDialogBase = QtWidgets.QDialog()
    ui = Ui_pluginmDialogBase()
    ui.setupUi(pluginmDialogBase)
    pluginmDialogBase.show()
    sys.exit(app.exec_())
